version: '3.7'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - '1883:1883'
    networks:
      - mosquitto-net
    volumes:
      - ./mosquitto/config:/mosquitto/config

networks:
  mosquitto-net:
